### ISSUE TITLE
깜짝 놀랄 일??

### ISSUE THREAD

**Issue by Yunsik-Choi** [Jeong-sky-1003/SpringStudy#1]
**2장** 멀티 스레드를 설명하는 **예제 2-7**에서 실행해 보면 결과를 보고 깜짝 놀라게 될 것이라고 하는데 정확히 어떤걸 의미하는지 잘 모르겠습니다.

**Comment by junbeom-kang** [comment]
![image](https://user-images.githubusercontent.com/59498625/111673549-6f449100-885e-11eb-8fc9-38147bb815b6.png)
 share를 다음과 같이 Thread의 메소드 this.getName()을 사용해서 출력하면
멀티스레드 0,1이 동시에 돌아가고 있으면서 전역변수를 동시에 사용하고 있어서 0~18까지 랜덤으로 가져가고
실행속도가 계속 바뀌어서 Thread의 출력순서도 무작위가 됩니다 .(실행할때마다 출력도 다릅니다)

**Comment by junbeom-kang** [comment]
> **2장** 멀티 스레드를 설명하는 **예제 2-7**에서 실행해 보면 결과를 보고 깜짝 놀라게 될 것이라고 하는데 정확히 어떤걸 의미하는지 잘 모르겠습니다.
![image](https://user-images.githubusercontent.com/59498625/111673549-6f449100-885e-11eb-8fc9-38147bb815b6.png)
 share를 다음과 같이 Thread의 메소드 this.getName()을 사용해서 출력하면
멀티스레드 0,1이 동시에 돌아가고 있으면서 전역변수를 동시에 사용하고 있어서 0~18까지 랜덤으로 가져가고
실행속도가 계속 바뀌어서 Thread의 출력순서도 무작위가 됩니다 .(실행할때마다 출력도 다릅니다)

**Comment by sky-Jeong** [comment]
준범님이 답변 주신 것처럼 Thread가 동시에 작동하며 share 변수를 공유하고 있어 깜짝 놀랄 일이라고 표현한 것 같습니다!

T 메모리 그려보시면 Thread가 별도로 생성되나, Static 영역은 공유하고 있어 이와 같은 일이 가능하기에 그런 것 같습니다.
코드에서 'sleep(1000);' 을 for문 밖이 아닌 출력문 바로 밑에 'sleep(2000)'과 같이 적정 시간으로 조정한 뒤 실행해보시면 아실거 같습니다!

https://youtu.be/ZCQY2e-kX9w

**Comment by Yunsik-Choi** [comment]
답변 감사합니다!
