### ISSUE TITLE
실전으로 추천해주실만한 강좌

### ISSUE THREAD

**Issue by choeunhak** [Jeong-sky-1003/SpringStudy#5]
스프링 실전 개발과 같은 강좌가 있을까요?
(clone coding같은 거면 너무 좋을 것 같습니다..)

유튜브 영어로 된 클론코딩이나 김영한님 실전개발강좌라던가 udemy 강좌 등 중에서 
들어보시거나 추천해주실만한 강좌 있을까요??

jpa나 spring security 사용된 강좌면 더욱 좋을것 같습니다.

**Comment by sky-Jeong** [comment]
추천에 대한 댓글은 아니오나.. 저도 한 번 찾아보고 좋은 강의 있으면 공유 코멘트 남기도록 하겠습니다!
