### ISSUE TITLE
[1주차 내용관련] 싱글턴 패턴 예제관련 질문드립니다!

### ISSUE THREAD

**Issue by sky-Jeong** [Jeong-sky-1003/SpringStudy#6]
먼저 질문 전, 발표 내용이 부족한 부분은 학습하며 내용을 정리해 추가하고 있습니다 ㅠㅠ 이에 업로드가 늦어져 정말 죄송합니다.
다시 정리하던 중 **제가 설계한 예제코드가 적절한지** 피드백을 받고 싶어 질문을 올립니다!
[https://sky-abraxas.tistory.com/26](정리 링크)

 - 만약, "아르바이트생은 매니저와 면담을 한다."라고 했을 때, 아래와 같이 구현했습니다.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/69142896/113398880-41248c80-93da-11eb-9599-3ccb1b76ddc0.png">

<img width="471" alt="image" src="https://user-images.githubusercontent.com/69142896/113398900-4aadf480-93da-11eb-8c5e-b77181b9076f.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/69142896/113398935-57324d00-93da-11eb-9ad4-f7bd172e506f.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/69142896/113399214-c90a9680-93da-11eb-9601-608f5b6a3c15.png">

<img width="562" alt="image" src="https://user-images.githubusercontent.com/69142896/113399186-be500180-93da-11eb-9fcc-ef94a47941f3.png">

 
 인터페이스는 '행위'를 나타낸다고 이해하여, Interviewable[인터페이스]로 인터뷰를 getInterview [getInterview( ) : String으로 return하는 메서드]를 선언하였습니다. 그리고 Interview 행위 자체를 클래스로 생성해, PartTime(아르바이트생)에서 상속 받아 구현하였습니다.

이 설계가 올바른 것인지, 혹은 틀린 내용이 있다면 피드백을 받고 싶습니다!

**Comment by Yunsik-Choi** [comment]
제 생각에는 abstract 메서드 자체가 하위 클래스에 구현을 강제하는 기능인데 하늘님이 구현하신거에서는 super클래스에서 구현되어있기 때문에 에러가 나지 않은걸로 보입니다. 이 설계에서 인터페이스를 상속받은 하위클래스가 직접 구현한 것이 아닌 하위 클래스가 상속받은 상위 추상 클래스에서 구현하면 PartTime 클래스 코드에서는 getInterview라는 메서드의 존재 자체를 확인 할 수 없기 때문에 좋은 설계는 아닌 것 같습니다. 즉 만약 저런 경우라면 이미 '행위'가 구현되어 있으므로 구지 인터페이스를 만들어 강제화 할 이유는 없을 것 같습니다!
